# Generated by Django 2.2.4 on 2021-04-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='categories',
            field=models.ManyToManyField(related_name='jobs', to='main_app.Category'),
        ),
        migrations.AlterField(
            model_name='job',
            name='other_jobs',
            field=models.ManyToManyField(related_name='jobs_added', to='main_app.User'),
        ),
    ]
